### ISSUE TITLE
您好，请问数据集还在嘛

### ISSUE THREAD

**Issue by AllenZYJ** [JackeyGuo/pytorch-classification-models#1]
作者您好，请问数据集还在嘛，能否共享一份，非常感谢您的回复

**Comment by JackeyGuo** [comment]
都在这个网盘里了
- 链接：https://pan.baidu.com/s/1yftyExMTygYkNRap40tIbg 
- 提取码：eitx

**Comment by AllenZYJ** [comment]
非常感谢

> 都在这个网盘里了
> 
> * 链接：https://pan.baidu.com/s/1yftyExMTygYkNRap40tIbg
> * 提取码：eitx

非常感谢您
